apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: springboot-sample
spec:
  tag: ccr.ccs.tencentyun.com/yanghaitao/springboot-sample
  serviceAccount: kpack
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/Poseidon1979/springboot-sample.git
      revision: master
