apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: springboot-sample
spec:
  tag: harbor.haas-468.pez.pivotal.io/spring_tkg_sample/springbootsample
  serviceAccount: kpack
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/Poseidon1979/springboot-sample.git
      revision: 6c5170468c0b0bd7f6964c7e33724be0e4b716fd
